import type { Experience } from "../../src/lib/data";

export const experiences: Experience[] = [
  {
    company: "Alexander's Antiques",
    role: "Lead Full-Stack Engineer · Freelance",
    period: "Jul 2026 – Nov 2026",
    summary:
      "Built a Manhattan gallery's own platform end to end — Next.js storefront, Vite staff workbench, and NestJS API — and launched it at alexanderantiques.com with 939 pieces migrated from 1stDibs.",
    highlights: [
      "Delivered ~130K LOC across storefront, admin, and a 138-route NestJS API, authoring 89% of commits behind a 4,300+ test quality gate.",
      "Shipped both apps on fixtures first, then cut over to the API through 16 repository ports; a parity suite proved all 83 methods before launch.",
      "Ran a report-first 1stDibs migration of 917 pieces into a four-level, 124-category taxonomy — idempotent, and refusing to write on a count mismatch.",
      "Built inquiry-not-checkout selling: phone-OTP collectors, six inquiry types, two-way threads with images, and staff letters logged with their trace.",
    ],
    metrics: [
      { value: "939", label: "pieces live" },
      { value: "4,300+", label: "automated tests" },
      { value: "83/83", label: "ports proven at cutover" },
    ],
    stack: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "NestJS",
      "PostgreSQL",
      "Drizzle",
      "Better Auth",
      "Turborepo",
      "Tailwind CSS",
      "Cloudflare R2",
      "Twilio",
      "Docker",
    ],
    link: "https://alexanderantiques.com",
  },
  {
    company: "Smart School · Maktabsoft",
    role: "Lead Frontend Engineer · Freelance",
    period: "Apr 2026 – Oct 2026",
    summary:
      "Rebuilt a school platform's mobile app from zero — one React codebase serving students and teachers on the web, as a PWA, and on Android, replacing an app with 180,000 installs.",
    highlights: [
      "Architected a 60K LOC feature-sliced app where the router assigns the role: 20 live student and teacher sections, frozen student URLs, no role branching in UI.",
      "Wrapped 99 legacy backend methods with 69 typed mappers and a ranked contract-exceptions record, where live probes overrode wrong documentation.",
      "Shipped silent auto-update across web, PWA, and a Capacitor Android shell, so web deploys reach Android with no store release.",
      "Built adaptive motion — a frame-rate probe assigns full, lite, or minimal per device — with 587 tests across mappers, hooks, and stores.",
    ],
    metrics: [
      { value: "180K", label: "installs on the app replaced" },
      { value: "20", label: "live sections, two roles" },
      { value: "587", label: "automated tests" },
    ],
    stack: [
      "React 19",
      "TypeScript",
      "Vite",
      "TanStack Router",
      "TanStack Query",
      "Zustand",
      "Zod",
      "Tailwind CSS",
      "Capacitor",
      "PWA",
      "Docker",
    ],
  },
  {
    company: "Restaurant Reservation Platform",
    role: "Full-Stack Engineer · Freelance, Part-Time",
    period: "Sep 2025 – Mar 2026",
    summary:
      "US-client reservation platform unifying event hall, catering, and table bookings into a 4-app monorepo with self-service booking flows and production observability.",
    highlights: [
      "Unified 3 booking channels into a 4-app monorepo with 21 customer/admin screens, replacing phone-based intake with self-service flows.",
      "Designed the reservation core — an 8-state lifecycle with transactional slot locking — preventing double-bookings and invalid transitions.",
      "Enforced single-source API contracts via 77 shared Zod schemas and 72 automated tests across auth, booking, and audit paths.",
      "Set up async BullMQ notifications (Twilio/Resend) off the HTTP path and a 9-service observability stack targeting p95 <500 ms.",
    ],
    metrics: [
      { value: "0", label: "double-bookings under load" },
      { value: "77", label: "shared API schemas" },
      { value: "72", label: "automated tests" },
    ],
    stack: [
      "TypeScript",
      "React",
      "Next.js",
      "Fastify",
      "PostgreSQL",
      "Redis",
      "BullMQ",
      "Docker",
      "Twilio",
    ],
  },
  {
    company: "RcoinX",
    role: "Senior Frontend Software Engineer",
    period: "Aug 2025 – Apr 2026",
    summary:
      "Architected the frontend platform for a pre-launch crypto exchange, from monorepo foundations to real-time Spot Trading and account-security flows.",
    highlights: [
      "Architected the frontend from scratch — Turborepo monorepo with 8 shared packages and strict Feature-Sliced Design import boundaries — authoring 61% of commits in a 3-engineer team.",
      "Delivered Spot Trading end-to-end (~9.5K LOC): order book, charts, order management, 9 REST integrations, and 3 WebSocket streams.",
      "Built a centralized WebSocket layer with ref-counted subscriptions, auto-reconnect, and 200–300ms throttled cache patching for market data.",
      "Shipped Account & Security with TOTP, WebAuthn, MFA-gated flows, RTL/LTR Storybook components, and Vitest + MSW tests in Docker CI.",
    ],
    metrics: [
      { value: "61%", label: "of frontend commits" },
      { value: "8", label: "shared packages" },
      { value: "3", label: "WebSocket streams" },
    ],
    stack: [
      "React 19",
      "TypeScript",
      "TanStack Router",
      "TanStack Query",
      "Zustand",
      "WebSocket",
      "Turborepo",
      "Tailwind CSS",
      "Radix UI",
      "Storybook",
      "Vitest",
      "MSW",
      "WebAuthn",
    ],
  },
  {
    company: "Isopoll",
    role: "Frontend Software Engineer",
    period: "Apr 2025 – Jul 2025",
    summary:
      "Frontend engineer on a fully RTL Persian B2B SaaS platform spanning surveys, recruitment, consultation booking, and digital commerce.",
    highlights: [
      "Engineered a 35K+ LOC, 41-page Next.js enterprise platform across 6 business modules in 4 months.",
      "Structured the data layer with 85 React Query hooks, 86 typed services, and 18 API domains, cutting new-endpoint work to one hook.",
      "Standardized 23+ production forms on 41+ Zod schemas, with hybrid SSR and tag-based revalidation across 31+ modules.",
    ],
    metrics: [
      { value: "41", label: "pages shipped" },
      { value: "86", label: "typed services" },
    ],
    stack: [
      "Next.js 15",
      "TypeScript",
      "App Router",
      "TanStack Query",
      "Zustand",
      "Zod",
      "React Hook Form",
      "Tailwind CSS",
      "Radix UI",
      "SSR",
      "Docker",
    ],
  },
  {
    company: "Propx",
    role: "Frontend Engineer · Freelance, Part-Time",
    period: "Apr 2025 – Jul 2025",
    summary:
      "Bilingual hedge fund platform — multi-step KYC onboarding, role-based dashboards, and a support ticketing system for customer verification workflows.",
    highlights: [
      "Developed an 11-step KYC wizard with in-browser ID capture and video recording, completed in a single web session.",
      "Delivered 18 role-gated screens across public, user, and super-admin areas, integrating the API through 30 typed hooks.",
      "Implemented a bilingual EN/FA interface with 633 strings in each language and 6 Zod-validated forms shared across auth, KYC, and ticket flows.",
    ],
    metrics: [
      { value: "11", label: "KYC steps, one session" },
      { value: "18", label: "pages across three roles" },
      { value: "633", label: "strings, in each language" },
    ],
    stack: [
      "Next.js 15",
      "React 19",
      "TypeScript",
      "Tailwind CSS",
      "shadcn/ui",
      "next-intl",
      "TanStack Query",
      "Zustand",
      "React Hook Form",
      "Zod",
      "Docker",
    ],
  },
  {
    company: "Chatomatic",
    role: "Co-Founder & Full-Stack Engineer",
    period: "Oct 2024 – Mar 2025",
    summary:
      "Co-founded and launched an AI assistant SaaS, then rebuilt the platform end-to-end with dashboard, playground, RAG retrieval, and a Shadow DOM embed.",
    highlights: [
      "Co-founded and launched to 100+ users; rebuilt it end-to-end solo in 2026 (~25K LOC) across dashboard, playground, and Shadow DOM embed.",
      "Built a greenfield Fastify API with 7 modules, 27 Result-typed use-cases, 11 tables, public embed routes, and per-assistant OpenAI/Ollama routing.",
      "Designed 2-phase streaming chat: pgvector top-5 retrieval, token stream, then post-stream citation persistence.",
      "Implemented hybrid RAG: IVFFlat top-5 retrieval with full-context fallback, inline numbered citations, and a 5-format ingestion pipeline.",
    ],
    metrics: [
      { value: "100+", label: "users at launch" },
      { value: "25K", label: "LOC rebuilt end-to-end" },
    ],
    stack: [
      "Next.js 15",
      "React 19",
      "TypeScript",
      "Fastify",
      "Vercel AI SDK",
      "OpenAI SDK",
      "pgvector",
      "Shadow DOM",
      "Vite",
      "Rollup",
      "next-intl",
    ],
  },
  {
    company: "IT Barbod",
    role: "Full-Stack Engineer",
    period: "Feb 2024 – Sep 2024",
    summary:
      "Led frontend delivery across three products in an on-site product team — a no-code app builder, a full-stack form builder, and an RTL markdown editor.",
    highlights: [
      "Built a drag-and-drop app builder enabling non-technical teams to ship React Native screens without engineering, cutting screen delivery from multi-day dev cycles to hours.",
      "Architected an RTL-first Markdown editor on Monaco with 24+ authoring commands.",
      "Created a schema-driven UI system with a Draft → Merge → Publish → Rollback lifecycle and a form builder with 11 field types on Next.js, Prisma, and PostgreSQL.",
    ],
    stack: [
      "React",
      "TypeScript",
      "Next.js",
      "Vite",
      "Tailwind CSS",
      "Radix UI",
      "dnd-kit",
      "Zod",
      "Prisma",
      "PostgreSQL",
      "Monaco Editor",
    ],
  },
  {
    company: "HeidaryHa",
    role: "Frontend Engineer · Contract",
    period: "2023 – 2024",
    summary:
      "Mobile banking PWA serving 14,000+ customers, with multi-factor auth and high-reliability financial transaction workflows.",
    highlights: [
      "Launched a production mobile-banking PWA serving 14,000+ customers, building its authentication and transaction flows.",
      "Contributed to a 40% increase in monthly loan applications, shipping PWA + Android from a single React/TypeScript codebase.",
    ],
    metrics: [
      { value: "14k+", label: "customers served" },
      { value: "40%", label: "more monthly applications" },
    ],
    stack: [
      "React",
      "TypeScript",
      "Vite",
      "TanStack Query",
      "PWA",
      "Capacitor",
      "Zod",
      "Tailwind CSS",
    ],
  },
  {
    company: "Motion Desk",
    role: "Software Engineer",
    period: "2021 – 2023",
    summary:
      "Collaborated with motion and product designers to build and publish two commercial Adobe After Effects extensions on aescripts.com.",
    highlights: [
      "Shipped 2 commercial cross-platform After Effects (CEP) extensions on aescripts.com.",
      "Reached 3,000+ downloads and 1,000+ sales by translating designer workflows into optimized extension UIs.",
    ],
    metrics: [
      { value: "3k+", label: "downloads" },
      { value: "1k+", label: "sales" },
    ],
    stack: ["JavaScript", "HTML", "CSS", "Adobe CEP", "After Effects"],
  },
];
